#!/bin/bash

##############################################################################
# PHP OPcache Optimization Script
# Enables and optimizes PHP OPcache for maximum performance
##############################################################################

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: Run as root (use sudo)${NC}"
    exit 1
fi

PHP_INI="/etc/php/8.3/fpm/php.ini"

echo -e "${YELLOW}Optimizing PHP OPcache...${NC}"

# Backup original
if [ ! -f "${PHP_INI}.backup-original" ]; then
    cp "$PHP_INI" "${PHP_INI}.backup-original"
    echo -e "${GREEN}✓ Backup created${NC}"
fi

# Create optimized OPcache config
cat > /etc/php/8.3/fpm/conf.d/99-opcache-optimization.ini << 'EOF'
; OPcache Optimization for Production
; Generated by RSU Bambudua optimization script

; Enable OPcache
opcache.enable=1
opcache.enable_cli=0

; Memory Settings
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000

; Performance Settings
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.fast_shutdown=1
opcache.enable_file_override=1

; Optimization Settings  
opcache.optimization_level=0x7FFFBFFF
opcache.save_comments=1
opcache.load_comments=1

; File Cache (optional - for better performance)
; opcache.file_cache=/var/www/opcache
; opcache.file_cache_only=0

; Huge Pages (if available)
opcache.huge_code_pages=0
EOF

echo -e "${GREEN}✓ OPcache configuration created${NC}"

# Realpath cache optimization
cat > /etc/php/8.3/fpm/conf.d/99-realpath-cache.ini << 'EOF'
; Realpath Cache Optimization
realpath_cache_size=4096K
realpath_cache_ttl=600
EOF

echo -e "${GREEN}✓ Realpath cache configuration created${NC}"

# Restart PHP-FPM
systemctl restart php8.3-fpm

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  OPcache Optimization Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Verify
echo -e "${YELLOW}OPcache Status:${NC}"
php -r "echo opcache_get_status() ? '✓ OPcache is ENABLED\n' : '✗ OPcache is DISABLED\n';" 2>/dev/null || php -i | grep "opcache.enable =>" | head -n 1

echo ""
echo -e "${YELLOW}Settings:${NC}"
php -i | grep -E "opcache.enable[^_]|opcache.memory_consumption|opcache.max_accelerated_files|opcache.validate_timestamps" | head -n 5

echo ""
echo -e "${YELLOW}💡 Note:${NC}"
echo "  • opcache.validate_timestamps=0 means faster but needs manual cache clear after code changes"
echo "  • After code updates, clear OPcache: sudo systemctl restart php8.3-fpm"
echo "  • Or use: php artisan opcache:clear (if opcache package installed)"
echo ""
